# -*- coding: utf-8 -*-
"""testcase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15H-Xi1YiRmOOar6VXjdqfN7EynIka9Un

## Import Modul untuk test case
"""

import modul as m

trnsct_123 = m.Transaction()

"""## Test Case 1 -- add_item"""

trnsct_123.add_item('Ayam Goreng', 2, 20000)
trnsct_123.add_item('Pasta Gigi', 3, 15000)

print('')
print('')

trnsct_123.show_order()

"""## Test Case 2 -- delete_item"""

trnsct_123.delete_item('Pasta Gigi')
print('')

trnsct_123.show_order()

"""##Test Case 3 -- reset_transaction"""

trnsct_123.reset_transaction()

trnsct_123.show_order()

"""## Test Case 4 -- total_price"""

trnsct_123.add_item('Ayam Goreng', 2, 20000)
trnsct_123.add_item('Pasta Gigi', 3, 15000)
trnsct_123.add_item('Mainan Mobil', 1, 200000)
trnsct_123.add_item('Mie Instan', 5, 3000)

trnsct_123.total_price()